### PR TITLE
[fix #574] deopt when binding is present in diff scope

### LINKED ISSUE #574: if statement wrongly removed when var declaration inside conditional block
It seems that when you declare and initialize a variable in a code block that executes conditionally, it is assumed that the variable will have this value also outside of the code block. This is wrong when the conditional code block does not get executed, in which case the variable will be undefined. As a result, further optimizations, like removing if statements, produce wrong results.

E.g., the following code produces a wrong result

```js
function x(v) {
  if (v) var w = true;
  if (w) console.log("hello",v);
}

x(false);
x(true);
```

It produces this:

```js
function x(a){if(a);console.log("hello",a)}x(!1),x(!0);
```

Which, when executed, outputs:

```
hello false
hello true
```

while it should only output the second line.

A related problem is with this code:

```js
function x(v) {
  if (v) {var w = [];for (let i=0;i<1;i++) w.push("hello");}
  if (w) for (let i=0;i<w.length;i++) console.log(w[i],v);
}

x(false);
x(true);
```

Which produces:

```js
function x(a){if(a){var b=[];for(let a=0;1>a;a++)b.push("hello")}for(let c=0;c<b.length;c++)console.log(b[c],a)}x(!1),x(!0);
```

When executed this throws an exception `Cannot read property 'length' of undefined`.

However, unlike the previous example, when disabling the `minify-dead-code-elimination` plugin, this produces correct code.

The latter example is what happens for example when processing the firebase scripts (see: https://github.com/Polymer/polymer-cli/issues/701)

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
+ Fix #574 

this is required for only var bindings. 

The other way we could fix this is to hoist all the var bindings before we run simplify & deadcode.

### CODE REVIEW

File: packages/babel-plugin-minify-dead-code-elimination/src/index.js [hunk 1]
```diff
@@ -285,14 +291,10 @@ module.exports = ({ types: t, traverse }) => {
               let replacementPath = binding.path;
               let isReferencedBefore = false;
 
-              if (binding.referencePaths.length > 1) {
```
Comment (vigneshshanmugam) [inline packages/babel-plugin-minify-dead-code-elimination/src/index.js]: unnecessary check.

File: packages/babel-plugin-minify-dead-code-elimination/src/index.js [hunk 2]
```diff
@@ -765,8 +767,21 @@ module.exports = ({ types: t, traverse }) => {
           const evalResult = test.evaluate();
           const isPure = test.isPure();
 
-          const replacements = [];
+          const { path: bindingPath } =
+            path.scope.getBinding(test.node.name) || {};
```
Comment (boopathi) [inline packages/babel-plugin-minify-dead-code-elimination/src/index.js]: don't use `|| {}` ?

Comment (boopathi) [inline packages/babel-plugin-minify-dead-code-elimination/src/index.js]: `if (binding)` check is clearer, like it's used everywhere else in babili

File: packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js [hunk 3]
```diff
@@ -2710,4 +2710,14 @@ describe("dce-plugin", () => {
     `);
     expect(transform(source)).toBe(expected);
   });
+
+  it("should deopt when binding is on different scope - issue #574", () => {
+    const source = unpad(`
+      function foo(v) {
+        if (v) var w = 10;
+        if (w) console.log("hello", v);
```
Comment (boopathi) [inline packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js]: There is also

```js
while (v) { var w = 10; }
if (w) console.log(w);
```

**Comment by vigneshshanmugam** [comment]
We need to handle this in simplify as well for the same case. 

Started to think, hoisting that var would be a better option than monkey patching at all places. Thoughts? @boopathi

**Comment by boopathi** [comment]
var hoisting was considered earlier. But I didn't try measuring its effect on gzip yet. https://github.com/babel/babili/issues/48#issuecomment-233697001

**Comment by vigneshshanmugam** [comment]
Hmm alright, the problem itself is with babel's `path.evaluate()` being truthy even for bindings present in different scope. 

It becomes tricky to do the scope check on every pattern matching step in simplify.
