### PR TITLE
Fix if_return & dce ifelse..return within loops

### LINKED ISSUE #257: if..return brings functions into block
### Input 

```js
function foo() {
  bar();
  if(x) return;
  const {a}=b;
  function bar () {
    baz();
    bar();
  }
}
```

### Output 

```js
function foo() {
  if (bar(), !x) {
    function c() {
      baz(), c();
    }

    const { a: d } = b;c();
  }
}
```

[REPL](https://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=false&presets=es2017&code=function%20foo()%20%7B%0A%20%20bar()%3B%0A%20%20if(x)%20return%3B%0A%20%20const%20%7Ba%7D%3Db%3B%0A%20%20function%20bar%20()%20%7B%0A%20%20%20%20baz()%3B%0A%20%20%20%20bar()%3B%0A%20%20%7D%0A%20%20bar()%3B%0A%7D&experimental=true&loose=false&spec=false)

### LINKED ISSUE #265: Infinite loop when simplify and deadcode used together
Input:

```js
function getParentConditionalPath(path) {
  let parentPath;
  while (parentPath = path.parentPath) {
    if (parentPath.isIfStatement() || parentPath.isConditionalExpression()) {
      if (path.key === "test") {
        return;
      } else {
        return parentPath;
      }
    } else {
      path = parentPath;
    }
  }
}
```

Output: 

```js
function getParentConditionalPath(path) {
  for (let parentPath; parentPath = path.parentPath;)
    if (!(parentPath.isIfStatement() || parentPath.isConditionalExpression()))
      path = parentPath;
    else if (path.key !== "test")
      return parentPath;
}
```

for `path.key === "test"` and the above condition fails, this causes an infinite loop where in the actual code, it simply returns undefined.

Reason:
Maybe because of if_return in simplify ... related #257

### LINKED ISSUE #275: minify-dead-code-elimination incorrectly removes return statement in a loop
Simplified repro:
```js
function remove(id) {
    for (var j = 0; j < array.length; ++j) {
        if (array[j] === id) {
            array.splice(j, 1);
            return;
        }
    }
}
```
Output:
```js
function remove(id) {
    for (var j = 0; j < array.length; ++j) {
        if (array[j] === id) {
            array.splice(j, 1);
        }
    }
}
```
In this case `return` is not dead code, since it terminates the loop. Interestingly `break` statement is not removed in the similar case.
[REPL link](https://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=false&presets=&experimental=true&loose=true&spec=true&code=function%20remove(id)%20%7B%0A%20%20%20%20for%20(var%20j%20%3D%200%3B%20j%20%3C%20array.length%3B%20%2B%2Bj)%20%7B%0A%20%20%20%20%20%20%20%20if%20(array%5Bj%5D%20%3D%3D%3D%20id)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20array.splice(j%2C%201)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D%0A)

### PR DESCRIPTION
**Pull request by boopathi**
+ (Close #265)
+ (Close #257)
+ (Close #275)

### CODE REVIEW

File: packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js [hunk 1]
```diff
@@ -2,13 +2,21 @@ jest.autoMockOff();
...
+const simplify = require("../../babel-plugin-minify-simplify/src/index");
 
 function transform(code, options, babelOpts) {
   return babel.transform(code,  Object.assign({}, {
-    plugins: [[require("../src/index"), options]],
+    plugins: [[deadcode, options]],
   }, babelOpts)).code.trim();
 }
 
+function transformWithSimplify(code) {
```
Comment (boopathi) [inline packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js]: I guess this is not necessary. Will remove it.

File: packages/babel-plugin-minify-simplify/__tests__/simplify-test.js [hunk 2]
```diff
@@ -573,10 +573,10 @@ describe("simplify-plugin", () => {
       }
       function bar(a) {
         if (!lol) try {
-          doThings();
-        } catch (e) {
-          doOtherThings();
-        }
+            doThings();
```
Comment (boopathi) [inline packages/babel-plugin-minify-simplify/__tests__/simplify-test.js]: I don't know why this happened.

**Comment by boopathi** [comment]
Failing test: regexp-constructors.
