### PR TITLE
Add fix for other types of nodes in referencePaths

### LINKED ISSUE #105: ModuleBuildError: Module build failed: TypeError: Cannot read property 'scope' of undefined
👋 - getting this setup with a reasonably sized production React app using Flow. All our babel versions are up-to-date.

Ran into this error, which traces back to:

https://github.com/babel/babili/blob/master/packages/babel-plugin-minify-dead-code-elimination/src/index.js#L212

Error is thrown from the entry point of the app:

``` jsx
/* @flow */
import React, { Component } from 'react'
import { Provider } from 'react-redux'
import { IntlProvider } from 'react-intl'
import routes from './routes'
import store from './store'

export default class App extends Component {

  static displayName = 'App';

  render() {
    return (
      <IntlProvider locale="en">
        <Provider store={store}>
          {routes}
        </Provider>
      </IntlProvider>
    )
  }
}
```

Stacktrace:
<details>

```
ModuleBuildError: Module build failed: TypeError: /Users/brendan/src/app/src/app.js: Cannot read property 'scope' of undefined
    at ReferencedIdentifier (/Users/brendan/src/app/node_modules/babel-plugin-minify-dead-code-elimination/lib/index.js:341:37)
    at newFn (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:318:17)
    at NodePath._call (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:161:17)
    at traverse (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:83:12)
    at NodePath.traverse (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/index.js:144:25)
    at /Users/brendan/src/app/node_modules/babel-plugin-minify-dead-code-elimination/lib/index.js:331:35
    at _loop3 (/Users/brendan/src/app/node_modules/babel-plugin-minify-dead-code-elimination/lib/index.js:396:16)
    at Object.enter (/Users/brendan/src/app/node_modules/babel-plugin-minify-dead-code-elimination/lib/index.js:404:23)
    at Object.newFn (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:318:17)
    at NodePath._call (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:161:17)
    at NodePath.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:161:17)
    at traverse (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:83:12)
    at NodePath.traverse (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/index.js:144:25)
    at PluginPass.Program (/Users/brendan/src/app/node_modules/babel-plugin-minify-dead-code-elimination/lib/index.js:769:14)
    at /Users/brendan/src/app/node_modules/webpack/lib/NormalModule.js:138:20
    at /Users/brendan/src/app/node_modules/loader-runner/lib/LoaderRunner.js:328:11
    at /Users/brendan/src/app/node_modules/loader-runner/lib/LoaderRunner.js:201:18
    at runSyncOrAsync (/Users/brendan/src/app/node_modules/loader-runner/lib/LoaderRunner.js:114:3)
    at iterateNormalLoaders (/Users/brendan/src/app/node_modules/loader-runner/lib/LoaderRunner.js:200:2)
    at /Users/brendan/src/app/node_modules/loader-runner/lib/LoaderRunner.js:173:4
    at Storage.finished (/Users/brendan/src/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)
    at /Users/brendan/src/app/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

</details>

`.babelrc`:
<details>

```
{
  "presets": ["es2015", "react"],
  "plugins": [
    "array-includes",
    "syntax-class-properties",
    "transform-class-properties",
    "transform-flow-strip-types",
    "transform-object-rest-spread",
    "transform-react-inline-elements",
    "transform-react-pure-class-to-function",
    "transform-react-remove-prop-types"
  ],
  "env": {
    "production": {
      "presets": ["babili"],
      "plugins": [
        "transform-runtime"
      ]
    },
    "development": {
      "plugins": [
        "transform-runtime",
        ["react-transform", {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
          }, {
            "transform": "react-transform-catch-errors",
            "imports": ["react", "redbox-react"]
          }]
        }]
      ]
    },
    "test": {
      "plugins": [
        ["transform-runtime", { "polyfill": false }]
      ]
    }
  }
}
```

</details>

Possibly related to these warnings, which only appear with babili turned on:

```
You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 6.8. To find out the caller, grep for this
        message and change it to a `console.trace()`.
```

Ran with `console.trace()`:
<details>

```
ModuleBuildError: Module build failed: TypeError: /Users/brendan/src/app/src/app.js: Cannot read property 'scope' of undefined
    at ReferencedIdentifier (/Users/brendan/src/app/node_modules/babel-plugin-minify-dead-code-elimination/lib/index.js:341:37)
    at newFn (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:318:17)
    at NodePath._call (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:161:17)
    at traverse (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:83:12)
    at NodePath.traverse (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/index.js:144:25)
    at /Users/brendan/src/app/node_modules/babel-plugin-minify-dead-code-elimination/lib/index.js:331:35
    at _loop3 (/Users/brendan/src/app/node_modules/babel-plugin-minify-dead-code-elimination/lib/index.js:396:16)
    at Object.enter (/Users/brendan/src/app/node_modules/babel-plugin-minify-dead-code-elimination/lib/index.js:404:23)
    at Object.newFn (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:318:17)
    at NodePath._call (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:161:17)
    at NodePath.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:161:17)
    at traverse (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:83:12)
    at NodePath.traverse (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/index.js:144:25)
    at PluginPass.Program (/Users/brendan/src/app/node_modules/babel-plugin-minify-dead-code-elimination/lib/index.js:769:14)
```

</details>

I tried implementing each plugin one-by-one, I get a similar error for `babel-plugin-minify-constant-folding`:

<details>

```
ModuleBuildError: Module build failed: TypeError: /Users/brendan/src/app/src/app.js: Cannot read property 'node' of undefined
    at Mangler.renameNew (/Users/brendan/src/app/node_modules/babel-plugin-minify-mangle-names/lib/index.js:188:26)
    at /Users/brendan/src/app/node_modules/babel-plugin-minify-mangle-names/lib/index.js:143:23
    at Array.map (native)
    at Scopable (/Users/brendan/src/app/node_modules/babel-plugin-minify-mangle-names/lib/index.js:135:16)
    at NodePath._call (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:161:17)
    at NodePath.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:161:17)
    at traverse (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:83:12)
    at NodePath.traverse (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/index.js:144:25)
    at Mangler.mangle (/Users/brendan/src/app/node_modules/babel-plugin-minify-mangle-names/lib/index.js:100:22)
    at Mangler.run (/Users/brendan/src/app/node_modules/babel-plugin-minify-mangle-names/lib/index.js:45:14)
    at PluginPass.Program (/Users/brendan/src/app/node_modules/babel-plugin-minify-mangle-names/lib/index.js:263:17)
    at newFn (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:161:17)
    at traverse (/Users/brendan/src/app/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:83:12)
    at /Users/brendan/src/app/node_modules/webpack/lib/NormalModule.js:138:20
    at /Users/brendan/src/app/node_modules/loader-runner/lib/LoaderRunner.js:328:11
    at /Users/brendan/src/app/node_modules/loader-runner/lib/LoaderRunner.js:201:18
    at runSyncOrAsync (/Users/brendan/src/app/node_modules/loader-runner/lib/LoaderRunner.js:114:3)
    at iterateNormalLoaders (/Users/brendan/src/app/node_modules/loader-runner/lib/LoaderRunner.js:200:2)
    at /Users/brendan/src/app/node_modules/loader-runner/lib/LoaderRunner.js:173:4
    at Storage.finished (/Users/brendan/src/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)
    at /Users/brendan/src/app/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

But with the following config (the preset minus the two plugins that cause issues), everything works well:

```
      "plugins": [
        "transform-runtime",
        "babel-plugin-transform-undefined-to-void",
        "babel-plugin-transform-simplify-comparison-operators",
        "babel-plugin-transform-property-literals",
        "babel-plugin-transform-minify-booleans",
        "babel-plugin-transform-merge-sibling-variables",
        "babel-plugin-transform-member-expression-literals",
        "babel-plugin-minify-type-constructors",
        "babel-plugin-minify-simplify",
        "babel-plugin-minify-replace",
        "babel-plugin-minify-infinity",
        "babel-plugin-minify-guarded-expressions",
        "babel-plugin-minify-flip-comparisons",
        "babel-plugin-minify-constant-folding"
      ]
```

### LINKED ISSUE #122: Unexpected UnaryExpression. Expected an Identifier
I'm seeing the above error when I have lots of nested if/else's with the occasional empty block.

<details>
  <summary>Stack trace if it's useful</summary>
```
Error: test.js: Unexpected UnaryExpression. Expected an Identifier
    at Mangler.renameNew (foo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:193:19)
    at foo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:143:23
    at Array.map (native)
    at Scopable (foo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:135:16)
    at NodePath._call (foo/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (foo/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (foo/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (foo/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (foo/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (foo/node_modules/babel-traverse/lib/context.js:190:19)

```
</details>

Minimum example I could come up with ([repl](https://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=false&presets=es2015&experimental=true&loose=false&spec=false&code=function%20foo()%20%7B%0A%20%20var%20a%2C%20b%2C%20c%3B%0A%20%20%0A%20%20if%20(a)%20%7B%0A%20%20%20%20if%20(b)%20%7B%0A%20%20%20%20%20%20if%20(c)%20%7B%7D%0A%20%20%20%20%7D%0A%20%20%7D%20else%20%7B%0A%20%20%20%20if%20(b)%20%7B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20if%20(c)%20%7B%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D))

```js
function foo() {
  var a, b, c;
  
  if (a) {
    if (b) {
      if (c) {}
    }
  } else {
    if (b) {
    } else {
      if (c) {}
    }
  }
}
```

Seems to be coming from the interaction of `minify-dead-code-elimination` and `minify-mangle-names` (both seem fine individually but fail when used together)

Error's being thrown [here](https://github.com/babel/babili/blob/e306bf1b644f004145f7771f599e2b97401c5eac/packages/babel-plugin-minify-mangle-names/src/index.js#L168) which suggests it might be an upstream Babel bug?

### PR DESCRIPTION
**Pull request by boopathi**
+ (Close #122)
+ (Close #105)

### CODE REVIEW

File: packages/babel-plugin-minify-mangle-names/__tests__/mangle-names-test.js [hunk 1]
```diff
@@ -873,4 +873,34 @@ describe("mangle-names", () => {
     `);
     expect(transform(source)).toBe(expected);
   });
+
+  it("should handle export declarations", () => {
```
Comment (boopathi) [inline packages/babel-plugin-minify-mangle-names/__tests__/mangle-names-test.js]: should add this to DCE as well... or shall I add it to preset tests ?

**Comment by boopathi** [comment]
regarding #122 , strangely it happens only for

```js
function foo () {
  var a;
  if (a) {} else { 
    b() 
  }
}
```

and not for

```js
function foo () {

  if (a) {} else { 
    b() 
  }
}
```

this is replaced to 

```js
function foo () {
  var a;
  if (!a) {
    b()
  }
}
```

and the referencePath of `a` is `!a` ...

File: packages/babel-preset-babili/__tests__/preset-tests.js [hunk 2]
```diff
@@ -0,0 +1,42 @@
+jest.autoMockOff();
+
+const babel = require("babel-core");
+const unpad = require("../../../utils/unpad");
+
+function transform(code, options = {}, sourceType = "script") {
```
Comment (kangax) [inline packages/babel-preset-babili/__tests__/preset-tests.js]: Maybe it would make sense to move `transform` to utils and share among tests to avoid duplication?

Comment (boopathi) [inline packages/babel-preset-babili/__tests__/preset-tests.js]: Yeah.. Like discussed here https://github.com/babel/babili/issues/76 ... separate PR for all these things ...

Comment (kangax) [inline packages/babel-preset-babili/__tests__/preset-tests.js]: Oh right, I forgot :) If you can make a PR for that, I'd gladly merge — would make tests a bit cleaner.
