### PR TITLE
DCE: Deopt impure statements in If.test

### LINKED ISSUE #385: Incorrect transformation on React project with both simplify and dead code elimination enabled
I couldn't make a minimal repro, but compiling my project with these two plugins enabled leads to the following error message (it's worth mentioning that babili is run on single fairly large file created by Webpack):

```
Uncaught TypeError: inst.render is not a function        ReactCompositeComponent.js:811
``` 

The issue doesn't manifest with either of the plugins disabled. I narrowed the bug to `createPrevExpressionEater("if")` in `simplify` whose result is removed by the `if (evaluateTest === false)` block in the `IfStatement` part of `dead-code-elimination`. 

If there's any diagnostic I can run to be more helpful I'd be happy to do so.

### PR DESCRIPTION
**Pull request by boopathi**
TODO:

+ [x] Test case for impure statements
+ [x] Preset test cases with other plugins ?

### Note:
**This moves IfStatement from program.traverse in DCE to DCEPlugin.visitor.**

+ (Fix #385)
+ Add isPure check to IfStatement visitor in DCE
+ Move IfStatement visitor from program.traverse to DCEPlugin.visitor - so that it executes for all IfStatements as babel traverse happens and NOT during the single pass within programPath.traverse in DCE. This eliminates the need for a second pass for things like the one mentioned in #385.

### CODE REVIEW

File: packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js [hunk 1]
```diff
@@ -2421,4 +2421,13 @@ describe("dce-plugin", () => {
...
     expect(transform(source)).toBe(expected);
   });
+
+  it("should deopt impure expressions in if statements", () => {
+    const source = unpad(`
+      if (a.b(), true) {
+        foo();
+      }
+    `);
+    expect(transform(source)).toBe(source);
```
Comment (boopathi) [inline packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js]: this can be improved.

**Comment by boopathi** [comment]
@kangax the failing tests are - getting `</script` instead of `<\\\\/script`
