### PR TITLE
Throw upgrade error when babel version is less than 6.14.0

### LINKED ISSUE #70: Set hard dependency on babel.version
The preset or cli or node api when used with previous versions of babel, due to the rename bugs and evaluate bugs, we will be introducing bugs in user code that will be hard to grok that it is a bug with babel. We need to either fix this somehow for mangle and evaluate in the minifier or set hard dependency that it bails out for older versions of babel.

### LINKED ISSUE #106: Webpack Issues
My installed packages:

```
"devDependencies": {
  "babel-core": "^6.13.2",
  "babel-loader": "^6.2.5",
  "babel-plugin-transform-es2015-modules-commonjs": "^6.14.0",
  "babel-preset-babili": "0.0.1",
  "babili": "0.0.3",
  "browserify-versionify": "^1.0.6",
  "ify-loader": "^1.0.3",
  "shader-loader": "^1.2.1",
  "webpack": "^1.13.2",
  "webpack-dev-server": "^1.14.1"
}
```

My babel loader config:

```
{
  test: /\.js$/,
  exclude: /(node_modules)/,
  loader: `babel`,
  query: {
    presets: [`babili`],
    plugins: [`transform-es2015-modules-commonjs`]
  }
}
```

Error upon running `webpack-dev-server --inline --colors`:

```
ERROR in ./script.js
Module build failed: Error: Cannot find module 'babel-types'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/babel-preset-babili/node_modules/babel-plugin-minify-mangle-names/lib/renamer.js:14:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
 @ multi main
```

I explicitly installed **babel-types**, and now get this error upon re-running:

```
ERROR in ./script.js
Module build failed: Error: Plugin 0 specified in "foreign" provided an invalid property of "name"
    at Plugin.init (/home/ubuntu/workspace/node_modules/babel-core/lib/transformation/plugin.js:138:13)
    at Function.normalisePlugin (/home/ubuntu/workspace/node_modules/babel-core/lib/transformation/file/options/option-manager.js:147:12)
    at /home/ubuntu/workspace/node_modules/babel-core/lib/transformation/file/options/option-manager.js:181:30
    at Array.map (native)
    at Function.normalisePlugins (/home/ubuntu/workspace/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
    at OptionManager.mergeOptions (/home/ubuntu/workspace/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
    at /home/ubuntu/workspace/node_modules/babel-core/lib/transformation/file/options/option-manager.js:289:14
    at /home/ubuntu/workspace/node_modules/babel-core/lib/transformation/file/options/option-manager.js:342:20
    at Array.map (native)
    at OptionManager.resolvePresets (/home/ubuntu/workspace/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
 @ multi main
```

### PR DESCRIPTION
**Pull request by boopathi**
+ (Close #70)
+ related #114
+ (Close #106)

### CODE REVIEW

File: packages/babel-preset-babili/src/index.js [hunk 1]
```diff
@@ -1,20 +1,53 @@
+const err = new Error("Babili is supported only for babel version >=6.14.0");
```
Comment (hzoo) [inline packages/babel-preset-babili/src/index.js]: We can be more specific here - babel is `babel-core`. Can explain you need to update babel-core, or cli, etc

File: packages/babel-preset-babili/src/index.js [hunk 2]
```diff
@@ -1,20 +1,53 @@
+const err = new Error("Babili requires babel-core>=6.14.0. Upgrade babel-core or tools dependent on babel-core to recent versions");
+
+function isVersion(versionStr) {
+  const version = versionStr.split(".").map((p) => parseInt(p));
+  if (version[0] >= 6 && version[1] >= 14) {
```
Comment (kangax) [inline packages/babel-preset-babili/src/index.js]: `return version[0] >= 6 && version[1] >= 14` ? :)

**Comment by kangax** [comment]
thanks!

File: packages/babel-preset-babili/src/index.js [hunk 3]
```diff
@@ -1,20 +1,50 @@
+const err = new Error("Babili requires babel-core>=6.14.0. Upgrade babel-core or tools dependent on babel-core to recent versions");
+
+function isVersion(versionStr) {
+  const version = versionStr.split(".").map((p) => parseInt(p));
+  return version[0] >= 6 && version[1] >= 14;
```
Comment (loganfsmyth) [inline packages/babel-preset-babili/src/index.js]: Should we do `=== 6` instead of  `>= 6`?

Comment (boopathi) [inline packages/babel-preset-babili/src/index.js]: this is reverted. because it seems not possible to check version in preset. 

But yeah, cool.. it should be `===6`

Comment (loganfsmyth) [inline packages/babel-preset-babili/src/index.js]: Oh weird. I'd have expected the version to show up properly.

Comment (boopathi) [inline packages/babel-preset-babili/src/index.js]: It does show up properly. But problems in supporting older versions.

+ Older versions of babel only accept an object
+ Newer versions when they accept an object with `key = plugins` don't execute `buildPreset` - so no plugin is applied in preset.
+ We use `name` property to measure performance of each plugin.
