### PR TITLE
fix: update outdated react url

### LINKED ISSUE #816: Outdated Benchmark URLs
The benchmarking script `scripts/benchmark.js` points to <https://unpkg.com/react/dist/react.js> as a benchmark, but the React team no longer provides a `dist/react.js` file. This causes an error when trying to run benchmarks.

To reproduce:

```sh
$ git clone --depth 1 https://github.com/babel/minify.git
$ cd minify
$ yarn install
$ npm run bootstrap
$ npm run build
$ ./scripts/benchmark.js
```

Error log [here](https://pastebin.com/h7CgRrRc).

### PR DESCRIPTION
**Pull request by ganes1410**
fixes #816 

minify

The above image shows the script successfully running.

### CODE REVIEW

File: scripts/benchmark.js [hunk 1]
```diff
@@ -20,7 +20,6 @@ const butternut = require("butternut");
 
 const ASSETS_DIR = path.join(__dirname, "benchmark_cache");
 const DEFAULT_ASSETS = {
-  "react.js": "https://unpkg.com/react/dist/react.js", // 120 kb
```
Comment (vigneshshanmugam) [inline scripts/benchmark.js]: we would like to keep react as a dep here since we use it for smoke tests. 

So please update with the new URL instead of removing it. You can find the relevant code here https://unpkg.com/react@16.3.1/

Comment (ganes1410) [reply scripts/benchmark.js]: @vigneshshanmugam should i update it with  `react.development.js ` or `react.production.js`  ??

Comment (boopathi) [reply scripts/benchmark.js]: use development.js

File: scripts/benchmark.js [hunk 2]
```diff
@@ -20,7 +20,7 @@ const butternut = require("butternut");
...
+  "react.js":"https://unpkg.com/react@16.3.1/umd/react.development.js",
```
[the remark this answers is not in the document]
Comment (ganes1410) [reply scripts/benchmark.js]: @vigneshshanmugam  i made required changes.sorry for the delay
