### PR TITLE
Fix crashing in simplify plugin. Deopt instead

### LINKED ISSUE #455: Crash minifying in babili 0.0.12
Minifying this in babili 0.0.12:

```
function foo(param)
{
	if (param === null)
		return;
	
	let thingA = param.a;
	let thingB = param.b;
	
	if (!thingA && !thingB)
		return;
	
	let thingC = param.c;
}
```

crashes with "TypeError: unknown: Cannot read property 'scope' of null".

That's a minimal repro, if you delete any lines from the function foo it doesn't reproduce any more.

### PR DESCRIPTION
**Pull request by boopathi**
+ Fix #455

### CODE REVIEW

File: packages/babel-plugin-minify-simplify/__tests__/simplify-test.js [hunk 1]
```diff
@@ -3152,4 +3152,32 @@ describe("simplify-plugin", () => {
...
+    );
+    const expected = unpad(
+      `
+      function foo(param) {
+        if (param !== null) {
+            let thingA = param.a;
+            let thingB = param.b;
+            if (thingA || thingB) {
+                let thingC = param.c;
+              }
```
Comment (vigneshshanmugam) [inline packages/babel-plugin-minify-simplify/__tests__/simplify-test.js]: indentation is screwed up here.

Comment (boopathi) [inline packages/babel-plugin-minify-simplify/__tests__/simplify-test.js]: yeah. Has happened before for if_return.
